[workspace]
members = [
    ".",
    "chess_base",
]

[package]
name = "lucky_chess"
version = "0.1.0"
edition = "2024"

[dependencies]
chess_base = { path = "chess_base" }
uci-parser = { version = "1.1.0", features = ["clamp-negatives", "validate-promotion-moves", "types", "parse-go-perft"] }

[build-dependencies]
chess_base = { path = "chess_base" }

[profile.release]
codegen-units = 1
lto = true
debug = true

[profile.dev]
opt-level = 1
