[workspace]
resolver = "2"
members = [
    "chess_core",
    "chess_engine",
    "chess_cli",
    "chess_web",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Razvan"]

[workspace.dependencies]
chess_core = { path = "chess_core" }
chess_engine = { path = "chess_engine" }
bitflags = "2.13.1"
uci-parser = { version = "1.1.0", features = ["clamp-negatives", "validate-promotion-moves", "types", "parse-go-perft"] }
fearless_simd = "0.7.0"

[profile.release]
codegen-units = 1
lto = "fat"
debug = true

[profile.dev]
opt-level = 1
