use std::process::Command;

fn main() {
    println!("cargo::rerun-if-changed=Cargo.toml");
    println!("cargo::rerun-if-changed=../Cargo.toml");

    let pkg_version = env!("CARGO_PKG_VERSION");
    let git_hash = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|output| {
            if output.status.success() {
                String::from_utf8(output.stdout)
                    .ok()
                    .map(|s| s.trim().to_string())
            } else {
                None
            }
        });

    let version_str = match git_hash {
        Some(hash) if !hash.is_empty() => format!("{pkg_version}-{hash}"),
        _ => pkg_version.to_string(),
    };

    let content = format!(
        "// Auto-generated by build.rs from Cargo.toml - do not edit manually\nexport const ENGINE_VERSION = '{version_str}';\n"
    );

    let _ = std::fs::write("www/version.js", content);
}
