[target.'cfg(target_family = "wasm")']
rustflags = [
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "debuginfo=0",
    "-C", "strip=symbols",
    "-C", "panic=abort",
    "-C", "target-feature=+simd128",
    "-C", "link-arg=-zstack-size=16777216",
]

[alias]
build-wasm = "build -p chess_web --target wasm32-unknown-unknown --release"

[env]
HIP_PATH = "/opt/rocm"
HSA_OVERRIDE_GFX_VERSION = "11.0.0"
MIRIFLAGS = "-Zmiri-disable-stacked-borrows"

