[target.'cfg(target_arch = "x86_64")']
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-fuse-ld=mold",
]

[target.'cfg(target_family = "wasm")']
rustflags = [
    "-C", "opt-level=3",
    "-C", "codegen-units=1",
    "-C", "debuginfo=0",
    "-C", "strip=symbols",
    "-C", "panic=abort",
    "-C", "target-feature=+simd128",
]

[alias]
build-wasm = "build -p chess_web --target wasm32-unknown-unknown --release"

[net]
git-fetch-with-cli = true

[env]
HIP_PATH = "/opt/rocm"
HSA_OVERRIDE_GFX_VERSION = "11.0.0"

