[package]
name = "chess_engine"
version.workspace = true
edition.workspace = true

[dependencies]
chess_core.workspace = true
fearless_simd.workspace = true
uci-parser = { version = "1.1.0", features = ["clamp-negatives", "types", "parse-go-perft"] }

[build-dependencies]
chess_core.workspace = true
